spring:
  application:
    name: deukgeun
  datasource:
    url: jdbc:mysql://localhost:3306/dgdb
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB
  rabbitmq:
    host: localhost
    port: 5672
  mvc:
    cors:
      allowed-origins: "*"
    # view:
    #   prefix: "/WEB-INF/views/"
    #   suffix: ".jsp"
    #   # jsp를 구동하기위해 추가

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    # html구동하기위해 추가

com:
  conan:
    upload:
      path: upload

server:
  port: 8282

# rabbitmq 값을 dynamic하게 사용하기 위한 값
rabbitmq:
  queue:
    name: dgQueue
    json:
      name: dqJsonQueue
  exchange:
    name: dgExchange
  routing:
    key: dgRoutingKey
    json:
      key: dgRoutingJsonKey
