spring:
  application:
    name: deukgeun
  datasource:
    url: jdbc:mysql://localhost:3306/dgdb
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB
  mvc:
    cors:
      allowed-origins: "*"
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"                             
    # html구동하기위해 추가

com:
  conan:
    upload:
      path: upload

server:
  port: 8282
